### ISSUE TITLE
A shape mismatch problem occurs during training (tmi-branch)

### ISSUE THREAD

**Issue by Wangjiashun321** [gaocong13/Projective-Spatial-Transformers#36]
The error message is:
RuntimeError: Given normalized_shape=[192], expected input with shape [*, 192], but got input of size[2, 256, 128]

The error occured when i train the proposed network in tmi-branch, and the specific error location is in the crossvit encoding layer.
The size of the input data is the default, i.e  model([2,1,128,128,128], [2,1,128,128], [2,6], [2,8,3])

How to fix it?

**Comment by Zh-Cancan** [comment]
I also encountered the same problem

This issue seems to be a version issue with cross vit, or the author has made modifications to the class definition of cross vit by adding a "channels" variable that can control the patch_dim parameter of the ImageEmbeder module in cross vit

I changed "patch_dim=3 * patch_size * * 2" to "patch_dim=2 * patch_size * * 2" to solve this problem

**Comment by Wangjiashun321** [comment]
> I also encountered the same problem
> 
> This issue seems to be a version issue with cross vit, or the author has made modifications to the class definition of cross vit by adding a "channels" variable that can control the patch_dim parameter of the ImageEmbeder module in cross vit
> 
> I changed "patch_dim=3 * patch_size * * 2" to "patch_dim=2 * patch_size * * 2" to solve this problem

Thank you very much and I agree with your assumption that the author changed the crossViT code! Now that it's up and running, hopefully it will converge to a satisfactory result...
